# Generated by Django 4.2.3 on 2023-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gradutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("cnic", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "degree_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("session_enrolment_date", models.DateField(blank=True, null=True)),
                ("session_completion_date", models.DateField(blank=True, null=True)),
                ("degree_no", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
