# Generated by Django 4.2.3 on 2023-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usagazet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradutes",
            name="roll_no",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
