# Generated by Django 4.2.3 on 2023-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usagazet", "0002_alter_gradutes_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradutes",
            name="session_completion_date",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="gradutes",
            name="session_enrolment_date",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
