# Generated by Django 4.2.3 on 2023-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usagazet", "0004_alter_gradutes_degree_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradutes",
            name="remark",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
